name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  go-unit-tests:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6 # https://github.com/marketplace/actions/checkout
      - name: Set up Go
        uses: actions/setup-go@v6 # https://github.com/marketplace/actions/setup-go-environment
        with:
          go-version-file: go.mod
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Build
        run: go build -v ./...
      - name: Test
        run: gotestsum -f github-actions
      - name: Lint
        uses: golangci/golangci-lint-action@v9 # https://github.com/marketplace/actions/golangci-lint
        with:
          version: v2.7.2     # https://github.com/golangci/golangci-lint/releases
          args: --timeout=5m  # https://github.com/golangci/golangci-lint-action/issues/308
